### ISSUE TITLE
Save and delete buttons

### ISSUE THREAD

**Issue by andrewminton** [Petertron/workspacer#3]
Is there any perticular reason why the action buttons are at the top of the page in workspacer?

Isn't it better to maintain a consistent workflow and follow the conventions of where these buttons are placed in the Symphony core?

I got confused as to where the actual buttons were when coming to complete a save of a template.

It's just an aesthetic thing, but wondered what your thoughts were?

**Comment by petertron** [comment]
I moved the name field and the buttons to the context area in order to save space. The advantage may not be apparent to anyone with a higher resolution monitor than what I have. My monitor has a resolution of a mere 1024 x 768 pixels, and I might not be the only one with that resolution. Now that the editor window is auto-sized  to fit the available height (which I think is definitely a good idea), the editor would be too small for some people if I had not put the name field and buttons where they are now. I do not think it is that bad that I have broken with convention, especially when there are some users who would like to have a save button at the top.
